CPM-1276 Upgrade TinyMCE
WitchBird/tinymce-dist pull request #5
Opened 2018-02-22 10:35 UTC by joeyrogues

https://contractlive.atlassian.net/browse/CPM-1276

Upgraded from 4.6.4 to 3.6.7

2018-02-26 08:51 UTC, ctjhoa approved these changes

2018-02-26 08:59 UTC, sebeq33 approved these changes

2018-02-26 09:26 UTC, thiberaw approved these changes

2018-03-02 15:37 UTC, ctjhoa requested changes
Tu peux squash tes commits et ne pas toucher au trailing whitespace stp

2018-03-12 13:14 UTC, merged